name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Images
        run: |
          docker compose -f docker-compose.yml build

      - name: Push Docker Images to Docker Hub
        run: |
          docker push copyauthors288/chessbet-backend:latest
          docker push copyauthors288/chessbet-ws:latest
          docker push copyauthors288/chessbet-frontend:latest

      - name: SSH into Server and Deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            cd /srv/docker-chessbet2/chess-bet
            docker stop copyauthors288/chessbet-backend-container
            docker rm copyauthors288/chessbet-backend-container
            docker stop copyauthors288/chessbet-frontend-container
            docker rm copyauthors288/chessbet-frontend-container
            docker stop copyauthors288/chessbet-ws-container
            docker rm copyauthors288/chessbet-ws-container
            docker rmi copyauthors288/chessbet-backend
            docker rmi copyauthors288/chessbet-frontend
            docker rmi copyauthors288/chessbet-ws
            docker compose -f docker-compose.yml up -d
